# Options
set -sg terminal-overrides ",*:RGB"
set -g mouse on
set -g renumber-windows on  # keep numbering sequential

# Options: start indexes from 1
set -g base-index 1
set -g pane-base-index 1

# Change prefix
unbind-key C-b
set -g prefix C-Space
bind-key C-Space send-prefix

# Reload config
bind-key r source-file ~/.config/tmux/tmux.conf \; \
display "Reloaded from ~/.config/tmux.conf"

# Theme: status
set -g status-position "top"
set -g status-style bg=default,fg=black,bright
set -g status-right "   "
set -g status-left "#[fg=blue,bright] ● #S #[fg=black,bright]| "

# Theme: status (windows)
set -g window-status-format " #I "
set -g window-status-current-format " #I "
set -g window-status-current-style "#{?window_zoomed_flag,fg=yellow,fg=blue\#,nobold}"
set -g window-status-bell-style "fg=red,nobold"

# Theme: status (messages)
set -g message-style "bg=blue,fg=black,fill=blue"

# Keybindings: split
bind v split-window -h -c "#{pane_current_path}"
bind h split-window -v -c "#{pane_current_path}"

# Smart pane switching with awareness of Vim splits.
# See: https://github.com/christoomey/vim-tmux-navigator
vim_pattern='(\S+/)?g?\.?(view|l?n?vim?x?|fzf)(diff)?(-wrapped)?'
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +${vim_pattern}$'"
bind-key -n 'M-h' if-shell "$is_vim" 'send-keys M-h'  'select-pane -L'
bind-key -n 'M-j' if-shell "$is_vim" 'send-keys M-j'  'select-pane -D'
bind-key -n 'M-k' if-shell "$is_vim" 'send-keys M-k'  'select-pane -U'
bind-key -n 'M-l' if-shell "$is_vim" 'send-keys M-l'  'select-pane -R'
tmux_version='$(tmux -V | sed -En "s/^tmux ([0-9]+(.[0-9]+)?).*/\1/p")'
if-shell -b '[ "$(echo "$tmux_version < 3.0" | bc)" = 1 ]' \
    "bind-key -n 'M-\\' if-shell \"$is_vim\" 'send-keys M-\\'  'select-pane -l'"
if-shell -b '[ "$(echo "$tmux_version >= 3.0" | bc)" = 1 ]' \
    "bind-key -n 'M-\\' if-shell \"$is_vim\" 'send-keys M-\\\\'  'select-pane -l'"

bind-key -T copy-mode-vi 'M-h' select-pane -L
bind-key -T copy-mode-vi 'M-j' select-pane -D
bind-key -T copy-mode-vi 'M-k' select-pane -U
bind-key -T copy-mode-vi 'M-l' select-pane -R
bind-key -T copy-mode-vi 'M-\' select-pane -l
