# Options
set -sg terminal-overrides ",*:RGB"
set -g mouse on
set -g renumber-windows on  # keep numbering sequential

# Options: start indexes from 1
set -g base-index 1
set -g pane-base-index 1

# Change prefix
unbind-key C-b
set -g prefix C-Space
bind-key C-Space send-prefix

# Reload config
bind-key r source-file ~/.config/tmux/tmux.conf \; \
display "Reloaded from ~/.config/tmux.conf"

# Theme: status
set -g status-position "top"
set -g status-style bg=default,fg=black,bright
set -g status-right "   "
set -g status-left "#[fg=blue,bright] ● #S #[fg=black,bright]| "

# Theme: status (windows)
set -g window-status-format " #I "
set -g window-status-current-format " #I "
set -g window-status-current-style "#{?window_zoomed_flag,fg=yellow,fg=blue\#,nobold}"
set -g window-status-bell-style "fg=red,nobold"

# Theme: status (messages)
set -g message-style "bg=blue,fg=black,fill=blue"

# Keybindings: split
bind h split-window -h -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"
bind v split-window -v -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
